data: 
  name: 'mvtec_ad'
  num_classes: 15
  
model_name: 'AdaCos'

dataset:
  name: 'MVTecMetricDataset'
  params:
    data_dir: 'data'
    csv_filename: 'csvs/metric_learning.csv'
    fold_idx: 0
    num_folds: 10

  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'validation'
    - mode: 'evaluation'
      split: 'get_embeddings'
    - mode: 'evaluation'
      split: 'evaluation'
    - mode: 'inference'
      split: 'inference'

transform:
  name: 'metric_transform'
  num_preprocessor: 8
  params:
    resize_to: (256, 256)

model:
  params:
    num_features: 512
    num_classes: 15
    encoder: 'resnet18'

checkpoint: checkpoint/best.score.pth

train:
  dir: 'train_dirs'
  log_step: 2
  batch_size: 16
  gradient_accumulation_step: 1
  num_epochs: 2
  num_keep_checkpoint: 2
  no_bias_decay: False
  encoder_lr_ratio: 0.1
  save_checkpoint_epoch: 1

evaluation:
  batch_size: 16

inference:
  split: 'inference'
  batch_size: 16
  output_path: 'outputs'
  cross_validation: True 
  reference_csv_filename: 'csvs/example.csv'

loss:
  name: 'FocalLoss'
  params: 
    gamma: 2

optimizer:
  name: 'Adam'
  params:
    lr: 0.001
    weight_decay: 0.1

scheduler:
  name: 'StepLR'
  params:
    step_size : 1

hooks:
  forward:
    name: 'DMLForwardHook'
  distance:
    name: 'CosineDistanceHook'
  metric: 
    name: 'DMLMetricHook'

