data: 
  name: 'mvtec_ad'

model_name: 'SAGAN'

dataset:
  name: 'MVTecUnsvDataset' 
  params:
    data_dir: 'data'
    csv_filename: 'csvs/unsv_learning.csv'
    target: 'screw'

  splits:
    - mode: 'train'
      split: 'train'
      folds: 0,
    - mode: 'validation'
      split: 'validation'
      folds: 1,
    - mode: 'evaluation'
      split: 'evaluation'
      folds: 1,
    - mode: 'inference'
      split: 'inference'
      folds: 2,

transform:
  name: 'unsv_transform'
  num_preprocessor: 8
  params:
    resize_to: (128, 128)
    is_flip: True

model:
  gan:
    name: SAGAN
    params:
      image_size: 128
      z_dim: 100
      conv_dim: 64
  encoder:
    name: ResEncoder
    params:
      image_size: 128
      z_dim: 100
      max_dim: 256
      n_res_block: 1

checkpoint: 
  g: g_checkpoint/epoch_1000.pth
  d: d_checkpoint/epoch_1000.pth
  e: e_checkpoint/epoch_0100.pth

train:
  adv_loss: 'wgan-gp'
  dir: 'train_dirs'
  log_step: 10
  image_log_step: 100
  batch_size: 8
  critic_iter : 1
  gen_iter : 1
  noisy_label_prob: 0.05
  lambda_gp: 10
  z_dim: 100
  num_epochs: 3000
  num_keep_checkpoint: 100
  no_bias_decay: False
  save_checkpoint_epoch: 50

  encoder:
    num_epochs: 100
    kappa: 1.


inference:
  split: 'inference'
  batch_size: 8
  use_feature_loss: False
  output_path: 'outputs'
  cross_validation: True 
  reference_csv_filename: 'example.csv'


optimizer:
  critic:
      name: 'Adam'
      params:
        lr: 0.0004
        betas: [0.5, 0.999]

  gen:
    name: 'Adam'
    params:
      lr: 0.0001
      betas: [0.5, 0.999]

  encoder:
    name: 'Adam'
    params:
      lr: 0.001

hooks:
  metric: 
    name: 'AEMetricHook'
  
