data: 
  name: 'mvtec_ad'

model_name: 'SSIMAE'

dataset:
  name: 'MVTecUnsvDataset'
  params:
    data_dir: 'data'
    target: 'bottle'
    csv_filename: 'csvs/unsv_learning.csv'

  splits:
    - mode: 'train'
      split: 'train'
      folds: 0,
    - mode: 'validation'
      split: 'validation'
      folds: 1,
    - mode: 'evaluation'
      split: 'evaluation'
      folds: 1,
    - mode: 'inference'
      split: 'inference'
      folds: 2,

transform:
  name: 'unsv_transform'
  num_preprocessor: 8
  params:
    resize_to: (256, 256)
    normalize: false

model:
  name: 'AutoEncoder'
  params:
    image_size: 256
    z_dim: 100
    max_dim: 512
    n_res_block: 2

checkpoint: checkpoint/epoch_0100.pth

train:
  dir: 'train_dirs'
  log_step: 2
  image_log_step: 5
  batch_size: 16
  num_epochs: 100
  num_keep_checkpoint: 10
  save_checkpoint_epoch: 10

evaluation:
  batch_size: 8

inference:
  split: 'inference'
  batch_size: 8
  output_path: 'outputs'
  cross_validation: True 
  reference_csv_filename: 'example.csv'

loss:
  name: SSIMLoss  

optimizer:
  name: 'SGD'
  params:
    lr: 0.001
    momentum: 0.9

scheduler:
  name: 'StepLR'
  params:
    step_size : 50

hooks:
  forward:
    name: 'AEForwardHook'
  metric:
    name: 'AEMetricHook'

