data: 
  name: 'cifar10'
  num_classes: 10

model_name: 'VanillaCNN'

dataset:
  name: 'CifarMetricDataset' 
  params:
    data_dir: 'data'
    csv_filename: 'csvs/metric_learning.csv'
    fold_idx: 1
    num_folds: 2
    anomaly_classes: ['bird', 'plane', 'cat']

  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'validation'
    - mode: 'evaluation'
      split: 'get_embeddings'
    - mode: 'evaluation'
      split: 'evaluation'
    - mode: 'inference'
      split: 'inference'

transform:
  name: 'metric_transform'
  num_preprocessor: 8
  params:
    resize_to: (32, 32)

model:
  params:
    num_features: 512
    num_classes: 10
    encoder: 'resnet18'

checkpoint: checkpoint/best.score.pth

train:
  dir: 'train_dirs'
  log_step: 2
  batch_size: 64
  gradient_accumulation_step: 1
  num_epochs: 10
  num_keep_checkpoint: 1
  no_bias_decay: False
  encoder_lr_ratio: 0.1
  save_checkpoint_epoch: 1

evaluation:
  batch_size: 128

inference:
  split: 'inference'
  batch_size: 128
  output_path: 'outputs'
  cross_validation: True 
  reference_csv_filename: 'csvs/example.csv'

loss:
  name: 'FocalLoss'
  params: 
    gamma: 2

optimizer:
  name: 'Adam'
  params:
    lr: 0.001

scheduler:
  name: 'StepLR'
  params:
    step_size : 5

hooks:
  forward:
    name: 'DMLForwardHook'
  distance:
    name: 'CosineDistanceHook'
  metric: 
    name: 'DMLMetricHook'

