dataset:
  name: 'MetricDataset'
  params:
    idx_fold: 0
    data_dir: 'data/mvtec_ad'
    csv_filename: 'csvs/metric_learning.csv'

  splits:
    - mode: 'train'
      split: 'train'
      folds: 1,2,3,4,5,6,7,8,9
    - mode: 'validation'
      split: 'validation'
      folds: 0,
    - mode: 'evaluation'
      split: 'get_embeddings'
      folds: 1,2,3,4,5,6,7,8,9
    - mode: 'evaluation'
      split: 'evaluation'
      folds: 0,
    - mode: 'inference'
      split: 'inference'
      folds: 0,

transform:
  name: 'metric_transform'
  num_preprocessor: 8
  params:
    resize_to: (256, 256)

model:
  name: 'AdaCos'
  params:
    num_features: 512
    num_classes: 15
    encoder: 'resnet18'

checkpoint: train_dirs/000/checkpoint/epoch_0005.pth

train:
  dir: 'train_dirs/000'
  log_step: 2
  batch_size: 8
  gradient_accumulation_step: 1
  num_epochs: 30
  num_keep_checkpoint: 5
  #no_bias_decay: True
  encoder_lr_ratio: 0.1
  save_checkpoint_epoch: 1

evaluation:
  batch_size: 8

inference:
  split: 'inference'
  batch_size: 8
  output_path: 'outputs/000/'
  cross_validation: True 
  reference_csv_filename: 'data/mvtec_ad/csvs/example.csv'

loss:
  name: 'FocalLoss'
  params: 
    gamma: 2

optimizer:
  name: 'AdamW'
  params:
    lr: 0.001
    weight_decay: 0.1

scheduler:
  name: 'StepLR'
  params:
    step_size : 10

hooks:
  distance:
    name: 'CosineDistanceHook'

