dataset:
  name: 'MetricDataset'
  params:
    idx_fold: 0
    data_dir: 'data/mvtec_ad'
    csv_filename: 'csvs/metric_learning.csv'

  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'valid'
      split: 'get_embeddings'
    - mode: 'valid'
      split: 'valid'

transform:
  name: 'metric_transform'
  num_preprocessor: 8
  params:
    resize_to: (256, 256)

model:
  name: 'AdaCos'
  params:
    num_features: 512
    num_classes: 15
    encoder: 'resnet18'

train:
  dir: 'train_dirs/000'
  log_step: 2
  batch_size: 8
  gradient_accumulation_step: 1
  num_epochs: 30
  num_keep_checkpoint: 5
  no_bias_decay: True
  save_checkpoint_epoch: 1
  encoder_lr_ratio: 0.1

evaluation:
  batch_size: 8

loss:
  name: 'FocalLoss'
  params: 
    gamma: 2

optimizer:
  name: 'AdamW'
  params:
    lr: 0.00025
    weight_decay: 0.01

scheduler:
  name: 'OneCycleLR'
  params:
    epochs: 30
    max_lr: 0.00025
    pct_start: 0.033
    steps_per_epoch: 568

hooks:
  forward:
    name: 'MetricForwardHook'

