seed: 686653144

dataset:
  name: 'UnsvDataset'
  params:
    data_dir: 'data/mvtec_ad'
    target: 'grid'
    csv_filename: 'csvs/unsv_learning.csv'

  splits:
    - mode: 'train'
      split: 'train'
      folds: 0,
    - mode: 'validation'
      split: 'validation'
      folds: 1,
    - mode: 'evaluation'
      split: 'evaluation'
      folds: 1,
    - mode: 'inference'
      split: 'inference'
      folds: 2,

transform:
  name: 'unsv_transform'
  num_preprocessor: 8
  params:
    resize_to: (256, 256)
    normalize: false

model:
  name: 'AutoEncoder'

checkpoint: train_dirs/SSIM-AE/checkpoint/best.score.pth

train:
  dir: 'train_dirs/SSIM-AE'
  log_step: 2
  image_log_step: 5
  batch_size: 8
  num_epochs: 200
  num_keep_checkpoint: 5
  save_checkpoint_epoch: 1

evaluation:
  batch_size: 8

inference:
  split: 'inference'
  batch_size: 8
  output_path: 'outputs/SSIM-AE/'
  cross_validation: True 
  reference_csv_filename: 'data/mvtec_ad/csvs/example.csv'

loss:
  name: SSIMLoss  

optimizer:
  name: 'Adam'
  params:
    lr: 0.001

scheduler:
  name: 'StepLR'
  params:
    step_size : 100

hooks:
  forward:
    name: 'AEForwardHook'
  metric:
    name: 'AEMetricHook'

